fos_rest:
    view:
        empty_content: 204
        view_response_listener: true
        failed_validation: HTTP_BAD_REQUEST
        formats:
            json: true
            xml: false
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    format_listener:
        rules:
          - {
                path: "/api",
                priorities: ["json"],
                fallback_format: json,
                prefer_extension: false,
            }
          - { path: "^/", stop: true, fallback_format: html }
    serializer:
        serialize_null: true
    exception:
        enabled: true
        map_exception_codes: true
        codes:
            'App\Model\Article\ArticleNotFound': 404
            'App\Model\Article\ErrorCreatingArticle': 400
        messages:
            'App\Model\Article\ArticleNotFound': true
            'App\Model\Article\ErrorCreatingArticle': true