monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

    # handlers:
    #     paypal:
    #         level: info
    #         type: stream
    #         path: "%kernel.logs_dir%/paypal_%kernel.environment%.log"
    #         channels: [paypal]

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: error
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
            deprecation:
                type: stream
                channels: [deprecation]
                path: php://stderr
            symfony_mailer:
                type: symfony_mailer
                from_email: "%app.mailer.from.email%"
                to_email: "gerardo@latteandcode.com"
                subject: "%env(resolve:MONOLOG_MAIL_SUBJECT)% An Error Occurred! %%message%%"
                level: critical
                formatter: monolog.formatter.html
                content_type: text/html